### ISSUE TITLE
As a student, I would like to see an example

### ISSUE THREAD

**Issue by ZioHimself** [IgorWolkov/flow-helper#1]
Hello, Ihor.
First of all, I would like to express my compliment: I can see some kind of service composition arising from the `flow.scala`. As far as I can notice, `routing.scala` attempts to set some sort of framework for data processing and error handling: I assume, that the usage of that would lay out routes of services, where router would decide, which route would the processing take.

Is a usage example coming up?

**Comment by IgorWolkov** [comment]
Thanks Zio.

I will provide several use cases of the flow and routing during this week. Both of this approaches I'm using in production.

**Comment by IgorWolkov** [comment]
Hi Zio,
You can find the first example here: https://github.com/IgorWolkov/flow-helper#flow-helper

**Comment by ZioHimself** [comment]
Thanks, now that was fast :)
